Добавлены разметки Главной и Каталога
htmlacademy-htmlcss/2000955-device-33 pull request #2
Opened 2022-02-10 10:51 UTC by NickolayNeretin

2022-02-12 04:55 UTC, helenastashina reviewed
В промоблоке не хватает разметки еще двух слайдов. Сам слайдер стоит сделать нумерованным списком. И номер из списка мы стилизуем в дальнейшем

2022-02-12 04:55 UTC, helenastashina commented on index.html
> +      <nav class="navigation-user">
Тег nav должен быть один на странице и показывать основную навигацию по сайту. Здесь его стоит убрать

2022-02-12 04:55 UTC, helenastashina commented on index.html
> +        <ul class="navigation-list">
Здесь можно оставить одним списком с Каталогом, визуальное отделение обыгрывается стилями

2022-02-12 04:55 UTC, helenastashina commented on index.html
> +        <h2 class="slider-number">01</h2>
Это однозначно не заголовок!

2022-02-12 04:55 UTC, helenastashina commented on index.html
> +        <table class="table-slider-item">
Здесь таблица семантически не подходит. Лучше абзацы с тегом span внутри

2022-02-12 04:55 UTC, helenastashina commented on index.html
> +    </section>
Не хватает разметки для остальных пунктов (гарантия, кредит)

2022-02-12 04:55 UTC, helenastashina commented on index.html
> +      <h2 class="delivery-on-order-title">Доставим редкий товар под заказ</h2>
Заголовок должен обозначать какой-то смысловой блок, здесь же просто информационная ссылка, поэтому замени на  span, например

2022-02-12 04:55 UTC, helenastashina commented on index.html
> +      <h2 class="newsletter-title">Подпишитесь<br>
br здесь лишний.

2022-02-12 04:55 UTC, helenastashina commented on index.html
> +        <input class="field"  placeholder="Ваш e-mail" type="email" name="newsletter-email" id="newsletter-email" required>
Не хватает label для input

2022-02-12 04:55 UTC, helenastashina commented on index.html
> +        <a class="footer-logo" href="#">
Здесь ссылка на главную

2022-02-12 04:55 UTC, helenastashina commented on index.html
> +      <a class="header-logo" href="#">
Ссылка на главную страницу

2022-02-12 04:55 UTC, helenastashina commented on index.html
> +      <div class="decor-element"></div>
Для декоративных элементов разметку не добавляем! Все через стили

2022-02-12 05:04 UTC, helenastashina requested changes
В промоблоке не хватает разметки еще двух слайдов. Сам слайдер семантичнее сделать нумерованным списком.

На все внешние ссылки (соцсети, сайт академии) нужно добавить атрибут target="_blank"

2022-02-12 05:04 UTC, helenastashina commented on catalog.html
> +    <header class="page-header">
Все исправления аналогичны главной

2022-02-12 05:04 UTC, helenastashina commented on catalog.html
> +          <li class="navigation-item">
Пропущен пункт с авторизованным пользователем

2022-02-12 05:04 UTC, helenastashina commented on catalog.html
> +          <h2 class="catalog-filter-title">Фильтр:</h2>
Данный заголовок обсудим в чате

2022-02-12 05:04 UTC, helenastashina commented on catalog.html
> +              <a class="button product-card-button visually-hidden" href="#">Подробнее</a>
Можно сделать всю карточку кликабельной, а по ховеру просто показывать текст Подробнее, не выделяя его в отдельную ссылку

2022-02-12 05:04 UTC, helenastashina commented on catalog.html
> +        <footer class="page-footer">
Замечания аналогично главной

2022-02-17 07:07 UTC, NickolayNeretin commented on index.html
> +      <nav class="navigation-user">
+

2022-02-17 07:22 UTC, NickolayNeretin commented on index.html
> +        <ul class="navigation-list">
Done!

2022-02-17 07:27 UTC, NickolayNeretin commented on index.html
> +        <h2 class="slider-number">01</h2>
Done!

Сделал параграфом.

2022-02-17 07:30 UTC, wannakey commented on index.html
> +        <table class="table-slider-item">
Done!

2022-02-17 07:30 UTC, NickolayNeretin commented on index.html
> +      <h2 class="newsletter-title">Подпишитесь<br>
Done!

2022-02-17 07:30 UTC, NickolayNeretin commented on index.html
> +        <a class="footer-logo" href="#">
Done!

2022-02-17 07:31 UTC, NickolayNeretin commented on index.html
> +      <a class="header-logo" href="#">
Done!

2022-02-17 07:31 UTC, NickolayNeretin commented on index.html
> +      <div class="decor-element"></div>
Done!

2022-02-18 08:06 UTC, wannakey commented on index.html
> +    </section>
Done!

2022-02-18 08:09 UTC, NickolayNeretin commented on index.html
> +      <h2 class="delivery-on-order-title">Доставим редкий товар под заказ</h2>
Done!

2022-02-18 08:18 UTC, NickolayNeretin commented on index.html
> +        <input class="field"  placeholder="Ваш e-mail" type="email" name="newsletter-email" id="newsletter-email" required>
Done!

2022-02-22 07:24 UTC, NickolayNeretin commented on catalog.html
> +    <header class="page-header">
Done!

2022-02-22 07:24 UTC, NickolayNeretin commented on catalog.html
> +          <li class="navigation-item">
Done!

2022-02-22 07:24 UTC, NickolayNeretin commented on catalog.html
> +          <h2 class="catalog-filter-title">Фильтр:</h2>
Done!

2022-02-22 07:24 UTC, NickolayNeretin commented on catalog.html
> +              <a class="button product-card-button visually-hidden" href="#">Подробнее</a>
Done!

2022-02-22 07:24 UTC, NickolayNeretin commented on catalog.html
> +        <footer class="page-footer">
Done!

2022-02-22 16:01 UTC, merged